use_frameworks!

target 'DTApplicationUpdateManager_Example' do
  pod 'DTApplicationUpdateManager', :path => '../'

  target 'DTApplicationUpdateManager_Tests' do
    inherit! :search_paths

    
  end
end
